function sesson(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("sesson-gift").style.display="block";
}
function first(){
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("home-content").style.display="block";
}
function deliver(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("delivers").style.display="block";
}
function abt(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("aboutus").style.display="block";
}
function term(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("terms").style.display="block";
}
function telecom(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("tell").style.display="block";
}
function heritages(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("heritage").style.display="block";
}
function companys(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("company").style.display="block";
}
function coffees(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("coffee").style.display="block";
}
function sources(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("ethical-source").style.display="block";
}
function supports(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("coffee-source").style.display="none";
    document.getElementById("formersup").style.display="block";
}
function coffeesrc(){
    document.getElementById("home-content").style.display="none";
    document.getElementById("delivers").style.display="none";
    document.getElementById("sesson-gift").style.display="none";
    document.getElementById("aboutus").style.display="none";
    document.getElementById("terms").style.display="none";
    document.getElementById("tell").style.display="none";
    document.getElementById("heritage").style.display="none";
    document.getElementById("company").style.display="none";
    document.getElementById("coffee").style.display="none";
    document.getElementById("ethical-source").style.display="none";
    document.getElementById("formersup").style.display="none";
    document.getElementById("coffee-source").style.display="block";
}
